#!/usr/bin/env bash
# build.sh — ask what to build, then build it.
#
#   ./build.sh                  # start a run
#   ./build.sh --dry-run        # print the plan, touch nothing
#   ./build.sh --resume         # re-attach a lead to an existing build/ run
#   ./build.sh --model claude-opus-5
#   ./build.sh --session beta   # a second run, fully isolated from the default (own build-beta/,
#                               # own Herdr session, own intercom group) — safe to run concurrently
#
# Creates ONE pane running the lead agent. The lead asks what to build (via the
# build-intake extension), refines the answer into build/MISSION.md, and then hires its own
# team with scripts/team.sh — so the cockpit grows from one pane to N as it decides.
#
# Verified against Atomic 0.9.13 and Herdr 0.8.0. Bash 3.2 safe.
set -euo pipefail

SESSION="cockpit"
PROVIDER="anthropic"
MODEL="claude-sonnet-5"
MODE="run"
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) MODE="dry-run" ;;
    --resume)  MODE="resume" ;;
    --session) SESSION="$2"; shift ;;
    --model)   MODEL="$2"; shift ;;
    --provider) PROVIDER="$2"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac; shift
done

# Reject empty or path-like session names before SESSION is used anywhere — an empty value
# would make `rm -rf "$HOME/.config/herdr/sessions/$SESSION"` below wipe every session's
# persisted state, not just this run's. `set -u` catches a missing value but not "".
case "$SESSION" in
  ""|.|..|*/*) echo "invalid --session name: '$SESSION'" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "$0")" && pwd)"
# Session-scoped so several builds can run at once without colliding: the default 'cockpit'
# session keeps build/ and intercom group 'cockpit'; any other --session gets its own
# build-<name>/ dir and its own intercom group, so two teams never share a broker group,
# an agent name, or a feed. BUILD_DIR / ATOMIC_INTERCOM_GROUP still override if set.
GROUP="${ATOMIC_INTERCOM_GROUP:-$SESSION}"
if [ "$SESSION" = "cockpit" ]; then BUILD="${BUILD_DIR:-$HERE/build}"; else BUILD="${BUILD_DIR:-$HERE/build-$SESSION}"; fi
LAUNCHDIR="$BUILD/.launch"
export PATH="$HOME/.local/bin:$PATH"
herdr(){ command herdr --session "$SESSION" "$@"; }

if [ "$MODE" = "dry-run" ]; then
  echo "════════════════════════════════════════════════════════════"
  echo " DRY RUN — nothing launched."
  echo " Session: $SESSION   ·   Intercom group: $GROUP"
  echo " Model:   $PROVIDER/$MODEL"
  echo " Build:   $BUILD"
  echo "════════════════════════════════════════════════════════════"
  echo "Would create ONE pane named 'lead' running Atomic with:"
  echo "  -e $HERE/atomic/extensions/herdr-state.ts"
  echo "  -e $HERE/atomic/extensions/build-intake.ts"
  echo "  -e $HERE/atomic/extensions/intercom-bridge.ts"
  echo "  --append-system-prompt <team/lead.md>"
  echo "  --append-system-prompt <team/TRANSPORT.md>"
  echo
  echo "The lead would then ask: \"What do you want to build today?\""
  echo "and hire its team with: scripts/team.sh add <role>"
  exit 0
fi

command -v herdr >/dev/null || { echo "herdr not found on PATH (run ./scripts/setup.sh)" >&2; exit 1; }
command -v atomic >/dev/null || { echo "atomic not found on PATH (run ./scripts/setup.sh)" >&2; exit 1; }
if ! atomic auth print-bearer-token --model "$MODEL" --provider "$PROVIDER" >/dev/null 2>&1; then
  echo "atomic has no usable credential for $PROVIDER/$MODEL — run 'atomic' then '/login'." >&2
  exit 1
fi

if [ "$MODE" = "run" ] && [ -f "$BUILD/IDEA.md" ]; then
  echo "build/ already holds a run (IDEA.md exists)." >&2
  echo "Use --resume to continue it, or move build/ aside to start fresh." >&2
  exit 1
fi

mkdir -p "$BUILD" "$LAUNCHDIR"

# One launcher script per agent, so the pane only ever receives a SINGLE LINE of text.
# Pasting a multi-line brief into a TUI would submit at the first newline; briefs travel as
# --append-system-prompt arguments instead.
#
# Deliberately NOT `exec`: keep a shell wrapping Atomic so an exit status reaches the
# scrollback, and tee stderr to a log, because a pane that dies takes its scrollback with it.
{
  echo '#!/usr/bin/env bash'
  echo "# generated by build.sh — starts the 'lead' agent"
  printf 'export ATOMIC_ROLE=%q\n' "lead"
  printf 'export ATOMIC_INTERCOM_GROUP=%q\n' "$GROUP"
  printf 'export BUILD_DIR=%q\n' "$BUILD"
  printf 'export TEAMCHAT_FEED=%q\n' "$BUILD/team-chat.log"
  printf 'export ATOMIC_PROVIDER=%q\n' "$PROVIDER"
  printf 'export ATOMIC_MODEL=%q\n' "$MODEL"
  printf 'export HERDR_SESSION=%q\n' "$SESSION"
  echo "cd \"$HERE\""
  printf 'atomic -e %q -e %q -e %q --provider %q --model %q -n lead \\\n' \
    "$HERE/atomic/extensions/herdr-state.ts" \
    "$HERE/atomic/extensions/build-intake.ts" \
    "$HERE/atomic/extensions/intercom-bridge.ts" "$PROVIDER" "$MODEL"
  printf '  --append-system-prompt "$(cat %q)" \\\n' "$HERE/team/lead.md"
  printf '  --append-system-prompt "$(cat %q)" \\\n' "$HERE/team/TRANSPORT.md"
  printf '  2> >(tee -a %q >&2)\n' "$LAUNCHDIR/lead.stderr.log"
  echo 'status=$?'
  echo "echo; echo \"[cockpit] the lead session exited (status \$status). Pane kept open.\""
  echo "echo \"[cockpit] stderr: $LAUNCHDIR/lead.stderr.log\""
  echo "echo \"[cockpit] restart with: bash $LAUNCHDIR/lead.sh\""
} > "$LAUNCHDIR/lead.sh"
chmod +x "$LAUNCHDIR/lead.sh"

herdr server stop >/dev/null 2>&1 || true
sleep 1
[ "$MODE" = "run" ] && rm -rf "$HOME/.config/herdr/sessions/$SESSION"
sleep 0.5
( cd "$HERE" && command herdr server --session "$SESSION" >/dev/null 2>&1 & )
WORKSPACE_READY=0
for _ in $(seq 1 40); do
  herdr workspace list 2>/dev/null | grep -q '"workspaces"' && { WORKSPACE_READY=1; break; }
  sleep 0.3
done
[ "$WORKSPACE_READY" = 1 ] || echo "warning: herdr server did not report workspaces ready within 12s — continuing anyway" >&2
# Only create a workspace if this session has none. `workspace create` is unconditional
# otherwise, and on --resume Herdr has already restored the previous run's workspace — so
# every resume was adding another empty "Cockpit" workspace beside the real one.
if ! herdr workspace list 2>/dev/null | grep -q '"workspace_id"'; then
  herdr workspace create --label "Cockpit" >/dev/null 2>&1 || true
fi

# A Herdr server restart — observed for real when an unrelated `herdr plugin uninstall`
# bounced the server mid-run — destroys the workspace and every agent pane, but
# build/.launch/*.pane records survive on disk. Left alone, team.sh's duplicate-role guard
# refuses to re-hire anyone ("$ROLE is already hired") pointing at panes that no longer exist,
# and its team-cap count includes the dead records too. Prune anything stale here: after the
# server is confirmed up (so `herdr pane list` is answerable) and before this script writes
# its own lead.pane below. Runs in both run-mode and resume-mode; in run-mode build/ is
# normally fresh so this is a no-op, but a leftover build/ from a killed run is exactly when
# it matters.
# A record is stale if its pane is gone OR the pane survived with no live agent in it.
# Pane existence alone is NOT the test. A Herdr server restart RESTORES the panes — labels and
# all — while every agent process inside them is dead. Checking only pane_id therefore pruned
# nothing in exactly the case that matters, and scripts/team.sh went on refusing to re-hire
# ("already hired") for agents that no longer existed. Observed directly: after a restart the
# implementer and verifier panes came back with agent_status "unknown" and a bare shell prompt.
#
# An agent that is genuinely alive reports working/idle/blocked/done through
# atomic/extensions/herdr-state.ts, so "unknown" is the signal for an empty pane. Pruning runs
# before this script starts anything, so a live agent can never be caught by it.
live_agent_panes(){
  herdr pane list 2>/dev/null | python3 -c "
import sys,json
try: panes=json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
for p in panes:
    if (p.get('agent_status') or 'unknown') != 'unknown':
        print(p['pane_id'])
"
}
if [ -d "$LAUNCHDIR" ]; then
  # An empty result with a zero exit means the server answered and no pane holds a live agent —
  # the normal resume case, where everything should be pruned. Only a non-zero exit (the server
  # could not be reached at all) suppresses pruning.
  if LIVE_AGENT_PANES="$(live_agent_panes)"; then
    # `|| true`: a glob matching no *.pane files would otherwise abort under set -e.
    PANE_RECORDS="$(ls "$LAUNCHDIR"/*.pane 2>/dev/null)" || true
    if [ -n "$PANE_RECORDS" ]; then
      for f in $PANE_RECORDS; do
        ROLE_NAME="$(basename "$f" .pane)"
        RECORDED_PANE="$(cat "$f" 2>/dev/null || true)"
        if [ -z "$RECORDED_PANE" ] || ! printf '%s\n' "$LIVE_AGENT_PANES" | grep -qxF "$RECORDED_PANE"; then
          echo "pruned stale record: $ROLE_NAME (pane ${RECORDED_PANE:-none} has no live agent) — the role can be hired again"
          rm -f "$f"
        fi
      done
    fi
  else
    # Cannot reach the server — do NOT prune. Deleting every record because the server is
    # unreachable would be worse than the bug this is fixing: it would make a merely-offline
    # server look identical to a destroyed workspace and wipe valid records.
    echo "warning: could not reach herdr to check for stale pane records — leaving $LAUNCHDIR/*.pane untouched" >&2
  fi
fi

# The root shell pane is NOT reliably panes[0]: Herdr plugin panes carry labels ("Sidebar",
# "Explorer", …) and may register first. Select on the ABSENCE of a label — but an unlabelled
# pane is not necessarily a FREE pane: a live agent's own pane (e.g. this script's own
# implementer/docs/researcher panes) carries no label either, and the side tabs opened by
# _open_side_tab (team-chat, kanban, team, workflows — see below) are also unlabelled and, since
# they run a viewer script rather than an Atomic agent, report agent_status "unknown" just like
# a genuinely empty pane would. Observed live: root_pane() picked w1:p2 (the team-chat tab) and
# would have renamed it 'lead' and started an Atomic lead process inside it.
#
# Matching on terminal_title to spot side tabs was tried and dropped: Herdr truncates long
# titles, and with this repo's path length the "./scripts/kanban.sh" suffix was already cut off
# in live testing — title matching silently stops working past some path length. tab_id is
# reliable instead: every _open_side_tab call creates a NEW tab, so side-tab panes always sit in
# a different tab_id from the main tab where build.sh and every hired agent run. Restrict the
# search to the main tab (the tab already holding labelled agent panes, or — before anyone is
# hired — the lowest-numbered tab) and exclude any pane with a live agent.
root_pane(){
  herdr pane list 2>/dev/null | python3 -c "
import sys,json
try: panes=json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
def tabnum(p):
    suf=(p.get('tab_id') or '').rsplit(':',1)[-1]
    return int(suf[1:]) if suf[:1]=='t' and suf[1:].isdigit() else 0
labelled_tabs={p['tab_id'] for p in panes if p.get('label')}
if labelled_tabs:
    main_tabs=labelled_tabs
else:
    mn=min((tabnum(p) for p in panes), default=0)
    main_tabs={p['tab_id'] for p in panes if tabnum(p)==mn}
def is_free(p):
    if p.get('label'): return False
    if (p.get('agent_status') or 'unknown') != 'unknown': return False
    if p.get('tab_id') not in main_tabs: return False
    return True
shells=[p for p in panes if is_free(p)]
if not shells: sys.exit(1)
print(sorted(shells,key=lambda p:p['pane_id'])[0]['pane_id'])
"
}
# On --resume the lead pane already carries the label 'lead' from a prior run (this script
# renamed it), so root_pane()'s unlabeled search would find nothing. Prefer the labelled pane;
# fall back to the unlabeled search only if no labelled pane exists yet.
lead_pane_by_label(){
  herdr pane list 2>/dev/null | python3 -c "
import sys,json
try: panes=json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
leads=[p for p in panes if p.get('label')=='lead']
if not leads: sys.exit(1)
print(sorted(leads,key=lambda p:p['pane_id'])[0]['pane_id'])
"
}
LEAD=""
if [ "$MODE" = "resume" ]; then
  for _ in $(seq 1 40); do
    LEAD="$(lead_pane_by_label || true)"
    [ -n "$LEAD" ] && break
    sleep 0.5
  done
fi
if [ -z "$LEAD" ]; then
  for _ in $(seq 1 40); do
    LEAD="$(root_pane || true)"
    [ -n "$LEAD" ] && break
    sleep 0.5
  done
fi
[ -n "$LEAD" ] || { echo "could not find a shell pane to start the lead in" >&2; exit 1; }

herdr pane rename "$LEAD" lead >/dev/null 2>&1 || true
echo "$LEAD" > "$LAUNCHDIR/lead.pane"

# Give tab 1 an explicit label so it doesn't read as a bare "1" in the tab bar, ambiguous
# next to the 'team' roster tab (UX finding 2, build/UX-REVIEW-2.md). Idempotent: skip if a
# tab already carries the 'crew' label (e.g. on --resume). Best-effort — never fails the run.
if ! herdr tab list 2>/dev/null | python3 -c "
import sys, json
try: tabs = json.load(sys.stdin)['result']['tabs']
except Exception: sys.exit(1)
sys.exit(0 if any(t.get('label') == 'crew' for t in tabs) else 1)
"; then
  LEAD_TAB="$(herdr pane list 2>/dev/null | python3 -c "
import sys, json
try: panes = json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
p = [x for x in panes if x['pane_id'] == '$LEAD']
print(p[0]['tab_id'] if p else '')
" 2>/dev/null || true)"
  [ -n "$LEAD_TAB" ] && herdr tab rename "$LEAD_TAB" crew >/dev/null 2>&1 || true
fi

herdr pane send-text "$LEAD" "bash $LAUNCHDIR/lead.sh" >/dev/null
herdr pane send-keys "$LEAD" Enter >/dev/null

# DO NOT add a pane-readiness poll here. An earlier version waited for the pane's title to
# start with "atomic", and it deadlocked on the first real run: build-intake.ts opens its
# popup during session_start, and while that dialog is open the pane title stays "bash
# .../lead.sh". The title never changes, so the poll always timed out, deleted lead.pane, and
# exited — leaving a live popup with no script left to send the kickoff once it was answered.
#
# The poll existed to gate a `/name lead` send. That send is still needed (see below, where it
# now happens once IDEA.md exists) — but it does not need a poll: the wait for IDEA.md below IS
# the readiness signal, since it cannot be satisfied unless Atomic booted, rendered the popup,
# and got an answer.
#
# Nothing may be sent to this pane before IDEA.md exists: anything typed while the dialog is
# open lands IN the popup and is submitted as the human's answer.

# The popup is now up in the lead's pane. Wait for the human to answer it, then kick the lead
# into refining. (If a future Atomic lets an extension self-start a turn, this poll becomes
# unnecessary — see atomic/extensions/build-intake.ts.)
echo
echo "════════════════════════════════════════════════════════════"
if [ "$MODE" = "resume" ]; then
  # On a resume IDEA.md already exists, so build-intake.ts stays quiet and the wait below
  # returns at once. Saying "answer the question" here described a popup that never appears.
  echo " Resuming. To watch the team, open another terminal and run:"
else
  echo " To see the popup and answer the question, open another"
  echo " terminal and run:"
fi
echo
printf ' %s\n' "  herdr --session $SESSION"
echo
echo "════════════════════════════════════════════════════════════"
echo
if [ "$MODE" = "resume" ]; then
  echo "Re-attaching the lead to the existing mission…"
else
  echo "Waiting for your answer — attach the cockpit with the command above, then answer the popup in it…"
fi
# Wait for the human to answer the intake popup. There is deliberately NO timeout here.
# The popup keeps the lead agent alive with the question on screen, and the two kickoff
# sends below are gated on IDEA.md existing — so giving up would strand a live agent that
# can still be answered, and --resume is unsafe then (it restarts the server and discards
# the typed answer). Wait as long as it takes; print a heartbeat so a long wait does not
# look like a hang. The human can abort with Ctrl-C, or stop the run from another terminal
# with: herdr --session $SESSION server stop
# The wait below is unbounded, so a human who gives up must get guidance instead of dying
# silently while the detached herdr server and the live lead pane keep running. On Ctrl-C or
# SIGTERM, print how to reach the still-live lead, then exit. Cleared right after the loop so
# the rest of the script keeps default signal behavior.
trap 'printf "\n[cockpit] Interrupted before you answered. The lead is still live in its pane.\n  Attach with:  herdr --session %s\n  Answer the question, then re-run: ./build.sh --resume\n  Or stop the run: herdr --session %s server stop\n" "$SESSION" "$SESSION" >&2; exit 130' INT TERM
WAITED=0
while [ ! -f "$BUILD/IDEA.md" ]; do
  sleep 1
  WAITED=$((WAITED + 1))
  if [ $((WAITED % 60)) -eq 0 ]; then
    printf '[cockpit] still waiting for your answer in the cockpit (%dm elapsed)…\n' "$((WAITED / 60))"
  fi
done
trap - INT TERM

if [ -f "$BUILD/IDEA.md" ]; then
  # Register the lead on the Intercom broker, NOW — the popup has closed (IDEA.md exists), so
  # this lands at Atomic's prompt instead of inside the dialog.
  #
  # This send is required, and an earlier version deleted it on the theory that `-n lead` at
  # launch already set the Intercom name. A real run disproved that: specialists could not
  # reach the lead at all, and the implementer sat in a `sleep` loop for 19 minutes reporting
  # "Lead still hasn't come online", with `intercom send lead` returning
  # "Message to \"lead\" was not delivered: Session not found". `-n` sets the session's display
  # name; only `/name` registers the Intercom presence name. Both are needed.
  #
  # Timing is the whole trick: sent any earlier it is typed into the intake popup and becomes
  # the human's answer. Sent here, it works. Do not move it in either direction.
  #
  # Sent TWICE with a gap: a live run reproduced this exact failure a second time (2026-08-16)
  # with no error surfaced anywhere — the send just silently didn't register. `/name` is
  # idempotent (re-sending an already-correct name is a no-op), so the second send is free
  # insurance against a one-off race, not a guaranteed fix — bash has no way to query the
  # Intercom broker to confirm registration actually took (no CLI exists outside a live Atomic
  # session), so real verification is also baked into the kickoff message below: the lead's
  # first action self-checks and self-heals if this still didn't take.
  herdr pane send-text "$LEAD" "/name lead" >/dev/null
  herdr pane send-keys "$LEAD" Enter >/dev/null
  sleep 2
  herdr pane send-text "$LEAD" "/name lead" >/dev/null
  herdr pane send-keys "$LEAD" Enter >/dev/null
  sleep 2

  SELFCHECK="Before anything else: run intercom({action:\"list\"}) and confirm the \"Current session\" entry shows your name as \"lead\", not an anonymous subagent-chat-<uuid> — a known intermittent bug (build.sh's /name registration can silently fail with no visible error). If it shows the anonymous form, self-heal via Bash: herdr pane send-text <your-own-pane-id> \"/name lead\" then herdr pane send-keys <your-own-pane-id> Enter (get your own pane id from herdr pane list, filtering for agent==\"lead\"), then re-check intercom list. Do not skip this — an unregistered lead is unreachable by every teammate and by the human's team-chat pane, silently."

  if [ -f "$BUILD/MISSION.md" ]; then
    # A mission already exists — this is a resume. It may already be human-confirmed, so do
    # NOT re-refine IDEA.md or re-run the confirmation gate; that would silently rewrite a
    # mission the human already approved. Just get the lead re-oriented and moving again.
    herdr pane send-text "$LEAD" "$SELFCHECK Resume. Re-read $BUILD/MISSION.md and $BUILD/ROSTER.md (if present) to recover context, then continue the mission from where it left off. Do NOT re-refine MISSION.md and do NOT re-run the human confirmation gate — treat the mission as already confirmed. Hire more specialists with scripts/team.sh add <role> only if the mission still needs them." >/dev/null
  else
    herdr pane send-text "$LEAD" "$SELFCHECK Begin. Your first action after the check above is to run /skill:prompt-engineer (invoke it, do not skip it), then use it to refine $BUILD/IDEA.md into $BUILD/MISSION.md, show me the mission for confirmation, and hire your team with scripts/team.sh add <role>." >/dev/null
  fi
  herdr pane send-keys "$LEAD" Enter >/dev/null
else
  # Defensive re-check, not an interrupt guard: reachable only if IDEA.md disappears between
  # the loop's last test and this line (TOCTOU). On Ctrl-C/SIGTERM the script dies inside the
  # wait loop above and never reaches here, so the kickoff sends cannot fire without a mission.
  echo "No IDEA.md — the intake wait was interrupted before you answered. Attach a" >&2
  echo "cockpit with:  herdr --session $SESSION" >&2
  echo "answer the question, then re-run: ./build.sh --resume" >&2
fi

# Open the team-chat, kanban, and team-roster tabs via one idempotent, best-effort-but-VISIBLE
# helper. Each tab: skip if a tab with that label already exists (e.g. on --resume); otherwise
# create it and run the viewer script in it. A `herdr` hiccup here must never fail the whole
# run, so failures are swallowed — but silently swallowing them left a tab simply missing with
# no clue why (see: kanban tab not appearing). Every failure now prints a one-line warning plus
# the exact manual-recovery command, so a miss is visible instead of a mystery.
#
# No $LAUNCHDIR/*.pane record is written for any of these: scripts/team.sh hires by splitting
# the newest $LAUNCHDIR/*.pane file, and a record here would make every hire land in this tab
# (and count against the agent cap) instead of the lead/hire grid. Find-by-label only.

_tab_has_label(){
  # _tab_has_label <label> — exit 0 if a tab with that label exists in `herdr tab list`.
  herdr tab list 2>/dev/null | python3 -c "
import sys, json
label = sys.argv[1]
def labelled(o):
    if isinstance(o, dict):
        return o.get('label') == label or any(labelled(v) for v in o.values())
    if isinstance(o, list):
        return any(labelled(v) for v in o)
    return False
try: sys.exit(0 if labelled(json.load(sys.stdin)) else 1)
except Exception: sys.exit(1)
" "$1"
}

_find_pane_id(){
  # _find_pane_id — reads a `herdr tab create` JSON response on stdin, prints the new pane id.
  python3 -c "
import sys, json
def find(o):
    if isinstance(o, dict):
        if 'pane_id' in o: return o['pane_id']
        for v in o.values():
            r = find(v)
            if r: return r
    if isinstance(o, list):
        for v in o:
            r = find(v)
            if r: return r
    return None
try: print(find(json.load(sys.stdin)) or '')
except Exception: pass
"
}

_open_side_tab(){
  # _open_side_tab <label> <cmd...> — idempotent create-and-run, with a visible warning and
  # exact manual-recovery command if creation or the viewer launch did not stick.
  LABEL="$1"; shift
  if _tab_has_label "$LABEL"; then return 0; fi
  PANE_ID="$(herdr tab create --label "$LABEL" --cwd "$HERE" --no-focus 2>/dev/null | _find_pane_id || true)"
  if [ -n "$PANE_ID" ]; then
    herdr pane run "$PANE_ID" "$@" >/dev/null 2>&1 || true
  fi
  if ! _tab_has_label "$LABEL"; then
    echo "Warning: the '$LABEL' tab did not open automatically. Reopen it by hand:" >&2
    echo "  herdr tab create --label $LABEL --cwd $HERE --no-focus" >&2
    echo "  herdr pane run <new-pane-id> $*" >&2
  fi
}

# Read-only "team chat" tab: the whole intercom conversation as one feed
# (intercom-bridge.ts writes it — see specs/2026-08-14-intercom-team-chat-pane.md).
_open_side_tab team-chat env "TEAMCHAT_FEED=$BUILD/team-chat.log" "ATOMIC_INTERCOM_GROUP=$GROUP" ./scripts/team-chat.sh

# Kanban board: every card's stage at a glance (cards live under build/BOARD/, written with
# scripts/board.sh — see docs/kanban.md). BUILD_DIR points the viewer at THIS run's board, so
# --session beta watches build-beta/.
_open_side_tab kanban env "BUILD_DIR=$BUILD" ./scripts/kanban.sh

# Team roster board: who was hired, why, and each agent's live state (working/blocked/idle/
# done). BUILD_DIR + HERDR_SESSION point the viewer at THIS run's roster and session.
_open_side_tab team env "BUILD_DIR=$BUILD" "HERDR_SESSION=$SESSION" ./scripts/team-status.sh

# Named workflow runs: a list of active + terminal /workflow runs (registered via
# scripts/workflow-register.sh), selectable for read-only stage detail. BUILD_DIR points the
# viewer at THIS run's registry, so --session beta watches build-beta/WORKFLOW-RUNS.md.
_open_side_tab workflows env "BUILD_DIR=$BUILD" ./scripts/workflow-tab.sh

if [ "$MODE" = "resume" ]; then
  HEADLINE=" The lead is back. It is re-reading the mission and continuing."
else
  HEADLINE=" The lead is live. It will ask what to build, then hire."
fi

cat <<EOF

════════════════════════════════════════════════════════════
$HEADLINE
════════════════════════════════════════════════════════════
 WATCH:    herdr --session $SESSION
 ROSTER:   cat $BUILD/ROSTER.md
 MISSION:  cat $BUILD/MISSION.md
 STOP:     herdr --session $SESSION server stop
 CHAT:     opens in the 'team-chat' tab · reopen: ./scripts/team-chat.sh
 BOARD:    opens in the 'kanban' tab · add cards: ./scripts/board.sh · reopen: ./scripts/kanban.sh
 TEAM:     live roster in the 'team' tab · reopen: ./scripts/team-status.sh
 WORKFLOWS: opens in the 'workflows' tab · register a run: ./scripts/workflow-register.sh · reopen: ./scripts/workflow-tab.sh

 Output lands in: $BUILD
EOF
