#!/usr/bin/env bash
# build.sh — ask what to build, then build it.
#
#   ./build.sh                  # start a run
#   ./build.sh --dry-run        # print the plan, touch nothing
#   ./build.sh --resume         # re-attach a lead to an existing build/ run
#   ./build.sh --model claude-opus-5
#
# Creates ONE pane running the lead agent. The lead asks what to build (via the
# build-intake extension), refines the answer into build/MISSION.md, and then hires its own
# team with scripts/team.sh — so the cockpit grows from one pane to N as it decides.
#
# Verified against Atomic 0.9.12 and Herdr 0.8.0. Bash 3.2 safe.
set -euo pipefail

SESSION="harness"
GROUP="harness"
PROVIDER="anthropic"
MODEL="claude-sonnet-5"
MODE="run"
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) MODE="dry-run" ;;
    --resume)  MODE="resume" ;;
    --session) SESSION="$2"; shift ;;
    --model)   MODEL="$2"; shift ;;
    --provider) PROVIDER="$2"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac; shift
done

# Reject empty or path-like session names before SESSION is used anywhere — an empty value
# would make `rm -rf "$HOME/.config/herdr/sessions/$SESSION"` below wipe every session's
# persisted state, not just this run's. `set -u` catches a missing value but not "".
case "$SESSION" in
  ""|.|..|*/*) echo "invalid --session name: '$SESSION'" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "$0")" && pwd)"
BUILD="$HERE/build"
LAUNCHDIR="$BUILD/.launch"
export PATH="$HOME/.local/bin:$PATH"
herdr(){ command herdr --session "$SESSION" "$@"; }

if [ "$MODE" = "dry-run" ]; then
  echo "════════════════════════════════════════════════════════════"
  echo " DRY RUN — nothing launched."
  echo " Session: $SESSION   ·   Intercom group: $GROUP"
  echo " Model:   $PROVIDER/$MODEL"
  echo " Build:   $BUILD"
  echo "════════════════════════════════════════════════════════════"
  echo "Would create ONE pane named 'lead' running Atomic with:"
  echo "  -e $HERE/atomic/extensions/herdr-state.ts"
  echo "  -e $HERE/atomic/extensions/build-intake.ts"
  echo "  --append-system-prompt <team/lead.md>"
  echo "  --append-system-prompt <team/TRANSPORT.md>"
  echo
  echo "The lead would then ask: \"What do you want to build today?\""
  echo "and hire its team with: scripts/team.sh add <role>"
  exit 0
fi

command -v herdr >/dev/null || { echo "herdr not found on PATH (run ./scripts/setup.sh)" >&2; exit 1; }
command -v atomic >/dev/null || { echo "atomic not found on PATH (run ./scripts/setup.sh)" >&2; exit 1; }
if ! atomic auth print-bearer-token --model "$MODEL" --provider "$PROVIDER" >/dev/null 2>&1; then
  echo "atomic has no usable credential for $PROVIDER/$MODEL — run 'atomic' then '/login'." >&2
  exit 1
fi

if [ "$MODE" = "run" ] && [ -f "$BUILD/IDEA.md" ]; then
  echo "build/ already holds a run (IDEA.md exists)." >&2
  echo "Use --resume to continue it, or move build/ aside to start fresh." >&2
  exit 1
fi

mkdir -p "$BUILD" "$LAUNCHDIR"

# One launcher script per agent, so the pane only ever receives a SINGLE LINE of text.
# Pasting a multi-line brief into a TUI would submit at the first newline; briefs travel as
# --append-system-prompt arguments instead.
#
# Deliberately NOT `exec`: keep a shell wrapping Atomic so an exit status reaches the
# scrollback, and tee stderr to a log, because a pane that dies takes its scrollback with it.
{
  echo '#!/usr/bin/env bash'
  echo "# generated by build.sh — starts the 'lead' agent"
  printf 'export ATOMIC_ROLE=%q\n' "lead"
  printf 'export ATOMIC_INTERCOM_GROUP=%q\n' "$GROUP"
  printf 'export BUILD_DIR=%q\n' "$BUILD"
  printf 'export ATOMIC_PROVIDER=%q\n' "$PROVIDER"
  printf 'export ATOMIC_MODEL=%q\n' "$MODEL"
  printf 'export HERDR_SESSION=%q\n' "$SESSION"
  echo "cd \"$HERE\""
  printf 'atomic -e %q -e %q --provider %q --model %q -n lead \\\n' \
    "$HERE/atomic/extensions/herdr-state.ts" \
    "$HERE/atomic/extensions/build-intake.ts" "$PROVIDER" "$MODEL"
  printf '  --append-system-prompt "$(cat %q)" \\\n' "$HERE/team/lead.md"
  printf '  --append-system-prompt "$(cat %q)" \\\n' "$HERE/team/TRANSPORT.md"
  printf '  2> >(tee -a %q >&2)\n' "$LAUNCHDIR/lead.stderr.log"
  echo 'status=$?'
  echo "echo; echo \"[harness] the lead session exited (status \$status). Pane kept open.\""
  echo "echo \"[harness] stderr: $LAUNCHDIR/lead.stderr.log\""
  echo "echo \"[harness] restart with: bash $LAUNCHDIR/lead.sh\""
} > "$LAUNCHDIR/lead.sh"
chmod +x "$LAUNCHDIR/lead.sh"

herdr server stop >/dev/null 2>&1 || true
sleep 1
[ "$MODE" = "run" ] && rm -rf "$HOME/.config/herdr/sessions/$SESSION"
sleep 0.5
( cd "$HERE" && command herdr server --session "$SESSION" >/dev/null 2>&1 & )
WORKSPACE_READY=0
for _ in $(seq 1 40); do
  herdr workspace list 2>/dev/null | grep -q '"workspaces"' && { WORKSPACE_READY=1; break; }
  sleep 0.3
done
[ "$WORKSPACE_READY" = 1 ] || echo "warning: herdr server did not report workspaces ready within 12s — continuing anyway" >&2
herdr workspace create --label "Harness" >/dev/null 2>&1 || true

# The root shell pane is NOT reliably panes[0]: Herdr plugin panes carry labels ("Sidebar",
# "Explorer", …) and may register first. Select on the ABSENCE of a label.
root_pane(){
  herdr pane list 2>/dev/null | python3 -c "
import sys,json
try: panes=json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
shells=[p for p in panes if not p.get('label')]
if not shells: sys.exit(1)
print(sorted(shells,key=lambda p:p['pane_id'])[0]['pane_id'])
"
}
# On --resume the lead pane already carries the label 'lead' from a prior run (this script
# renamed it), so root_pane()'s unlabeled search would find nothing. Prefer the labelled pane;
# fall back to the unlabeled search only if no labelled pane exists yet.
lead_pane_by_label(){
  herdr pane list 2>/dev/null | python3 -c "
import sys,json
try: panes=json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
leads=[p for p in panes if p.get('label')=='lead']
if not leads: sys.exit(1)
print(sorted(leads,key=lambda p:p['pane_id'])[0]['pane_id'])
"
}
LEAD=""
if [ "$MODE" = "resume" ]; then
  for _ in $(seq 1 40); do
    LEAD="$(lead_pane_by_label || true)"
    [ -n "$LEAD" ] && break
    sleep 0.5
  done
fi
if [ -z "$LEAD" ]; then
  for _ in $(seq 1 40); do
    LEAD="$(root_pane || true)"
    [ -n "$LEAD" ] && break
    sleep 0.5
  done
fi
[ -n "$LEAD" ] || { echo "could not find a shell pane to start the lead in" >&2; exit 1; }

herdr pane rename "$LEAD" lead >/dev/null 2>&1 || true
echo "$LEAD" > "$LAUNCHDIR/lead.pane"

herdr pane send-text "$LEAD" "bash $LAUNCHDIR/lead.sh" >/dev/null
herdr pane send-keys "$LEAD" Enter >/dev/null

ATOMIC_UP=0
for _ in $(seq 1 60); do
  if herdr pane list 2>/dev/null | python3 -c "
import sys,json
p=[x for x in json.load(sys.stdin)['result']['panes'] if x['pane_id']=='$LEAD']
sys.exit(0 if p and (p[0].get('terminal_title_stripped') or '').startswith('atomic') else 1)
" 2>/dev/null; then ATOMIC_UP=1; break; fi
  sleep 1
done
[ "$ATOMIC_UP" = 1 ] || {
  rm -f "$LAUNCHDIR/lead.pane"
  echo "Atomic did not reach its prompt in the lead pane within 60s." >&2
  echo "Removed $LAUNCHDIR/lead.pane so this can be retried. Inspect the pane, then restart" >&2
  echo "it with: bash $LAUNCHDIR/lead.sh" >&2
  exit 1; }

# NOTE: unlike scripts/team.sh, this script must NOT send a `/name` command here. `-n lead`
# at launch (above) already sets the session's name, and by this point build-intake.ts has
# opened its `ctx.ui.input(...)` popup in the lead's pane (session_start fires before the
# readiness poll below can return) — anything typed into the pane now lands IN the popup,
# not at a shell or Atomic prompt. Nothing may be sent to this pane until IDEA.md exists.
sleep 2

# The popup is now up in the lead's pane. Wait for the human to answer it, then kick the lead
# into refining. (If a future Atomic lets an extension self-start a turn, this poll becomes
# unnecessary — see atomic/extensions/build-intake.ts.)
echo
echo "════════════════════════════════════════════════════════════"
echo " To see the popup and answer the question, open another"
echo " terminal and run:"
echo
printf ' %s\n' "  herdr --session $SESSION"
echo
echo "════════════════════════════════════════════════════════════"
echo
echo "Waiting for your answer in the attached cockpit…"
for _ in $(seq 1 600); do
  [ -f "$BUILD/IDEA.md" ] && break
  sleep 1
done

if [ -f "$BUILD/IDEA.md" ]; then
  if [ -f "$BUILD/MISSION.md" ]; then
    # A mission already exists — this is a resume. It may already be human-confirmed, so do
    # NOT re-refine IDEA.md or re-run the confirmation gate; that would silently rewrite a
    # mission the human already approved. Just get the lead re-oriented and moving again.
    herdr pane send-text "$LEAD" "Resume. Re-read $BUILD/MISSION.md and $BUILD/ROSTER.md (if present) to recover context, then continue the mission from where it left off. Do NOT re-refine MISSION.md and do NOT re-run the human confirmation gate — treat the mission as already confirmed. Hire more specialists with scripts/team.sh add <role> only if the mission still needs them." >/dev/null
  else
    herdr pane send-text "$LEAD" "Begin. Read $BUILD/IDEA.md, refine it into $BUILD/MISSION.md with /skill:prompt-engineer, show me the mission for confirmation, then hire your team with scripts/team.sh add <role>." >/dev/null
  fi
  herdr pane send-keys "$LEAD" Enter >/dev/null
else
  echo "No IDEA.md after 10 minutes. Attach a cockpit with:" >&2
  echo "  herdr --session $SESSION" >&2
  echo "Then re-run: ./build.sh --resume" >&2
fi

cat <<EOF

════════════════════════════════════════════════════════════
 The lead is live. It will ask what to build, then hire.
════════════════════════════════════════════════════════════
 WATCH:    herdr --session $SESSION
 ROSTER:   cat $BUILD/ROSTER.md
 MISSION:  cat $BUILD/MISSION.md
 STOP:     herdr --session $SESSION server stop

 Output lands in: $BUILD
EOF
