#!/usr/bin/env bash
# build.sh — ask what to build, then build it.
#
#   ./build.sh                  # start a run
#   ./build.sh --dry-run        # print the plan, touch nothing
#   ./build.sh --resume         # re-attach a lead to an existing build/ run
#   ./build.sh --model claude-opus-5
#
# Creates ONE pane running the lead agent. The lead asks what to build (via the
# build-intake extension), refines the answer into build/MISSION.md, and then hires its own
# team with scripts/team.sh — so the cockpit grows from one pane to N as it decides.
#
# Verified against Atomic 0.9.12 and Herdr 0.8.0. Bash 3.2 safe.
set -euo pipefail

SESSION="harness"
GROUP="harness"
PROVIDER="anthropic"
MODEL="claude-sonnet-5"
MODE="run"
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) MODE="dry-run" ;;
    --resume)  MODE="resume" ;;
    --session) SESSION="$2"; shift ;;
    --model)   MODEL="$2"; shift ;;
    --provider) PROVIDER="$2"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac; shift
done

# Reject empty or path-like session names before SESSION is used anywhere — an empty value
# would make `rm -rf "$HOME/.config/herdr/sessions/$SESSION"` below wipe every session's
# persisted state, not just this run's. `set -u` catches a missing value but not "".
case "$SESSION" in
  ""|.|..|*/*) echo "invalid --session name: '$SESSION'" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "$0")" && pwd)"
BUILD="$HERE/build"
LAUNCHDIR="$BUILD/.launch"
export PATH="$HOME/.local/bin:$PATH"
herdr(){ command herdr --session "$SESSION" "$@"; }

if [ "$MODE" = "dry-run" ]; then
  echo "════════════════════════════════════════════════════════════"
  echo " DRY RUN — nothing launched."
  echo " Session: $SESSION   ·   Intercom group: $GROUP"
  echo " Model:   $PROVIDER/$MODEL"
  echo " Build:   $BUILD"
  echo "════════════════════════════════════════════════════════════"
  echo "Would create ONE pane named 'lead' running Atomic with:"
  echo "  -e $HERE/atomic/extensions/herdr-state.ts"
  echo "  -e $HERE/atomic/extensions/build-intake.ts"
  echo "  -e $HERE/atomic/extensions/intercom-bridge.ts"
  echo "  --append-system-prompt <team/lead.md>"
  echo "  --append-system-prompt <team/TRANSPORT.md>"
  echo
  echo "The lead would then ask: \"What do you want to build today?\""
  echo "and hire its team with: scripts/team.sh add <role>"
  exit 0
fi

command -v herdr >/dev/null || { echo "herdr not found on PATH (run ./scripts/setup.sh)" >&2; exit 1; }
command -v atomic >/dev/null || { echo "atomic not found on PATH (run ./scripts/setup.sh)" >&2; exit 1; }
if ! atomic auth print-bearer-token --model "$MODEL" --provider "$PROVIDER" >/dev/null 2>&1; then
  echo "atomic has no usable credential for $PROVIDER/$MODEL — run 'atomic' then '/login'." >&2
  exit 1
fi

if [ "$MODE" = "run" ] && [ -f "$BUILD/IDEA.md" ]; then
  echo "build/ already holds a run (IDEA.md exists)." >&2
  echo "Use --resume to continue it, or move build/ aside to start fresh." >&2
  exit 1
fi

mkdir -p "$BUILD" "$LAUNCHDIR"

# One launcher script per agent, so the pane only ever receives a SINGLE LINE of text.
# Pasting a multi-line brief into a TUI would submit at the first newline; briefs travel as
# --append-system-prompt arguments instead.
#
# Deliberately NOT `exec`: keep a shell wrapping Atomic so an exit status reaches the
# scrollback, and tee stderr to a log, because a pane that dies takes its scrollback with it.
{
  echo '#!/usr/bin/env bash'
  echo "# generated by build.sh — starts the 'lead' agent"
  printf 'export ATOMIC_ROLE=%q\n' "lead"
  printf 'export ATOMIC_INTERCOM_GROUP=%q\n' "$GROUP"
  printf 'export BUILD_DIR=%q\n' "$BUILD"
  printf 'export TEAMCHAT_FEED=%q\n' "$BUILD/team-chat.log"
  printf 'export ATOMIC_PROVIDER=%q\n' "$PROVIDER"
  printf 'export ATOMIC_MODEL=%q\n' "$MODEL"
  printf 'export HERDR_SESSION=%q\n' "$SESSION"
  echo "cd \"$HERE\""
  printf 'atomic -e %q -e %q -e %q --provider %q --model %q -n lead \\\n' \
    "$HERE/atomic/extensions/herdr-state.ts" \
    "$HERE/atomic/extensions/build-intake.ts" \
    "$HERE/atomic/extensions/intercom-bridge.ts" "$PROVIDER" "$MODEL"
  printf '  --append-system-prompt "$(cat %q)" \\\n' "$HERE/team/lead.md"
  printf '  --append-system-prompt "$(cat %q)" \\\n' "$HERE/team/TRANSPORT.md"
  printf '  2> >(tee -a %q >&2)\n' "$LAUNCHDIR/lead.stderr.log"
  echo 'status=$?'
  echo "echo; echo \"[harness] the lead session exited (status \$status). Pane kept open.\""
  echo "echo \"[harness] stderr: $LAUNCHDIR/lead.stderr.log\""
  echo "echo \"[harness] restart with: bash $LAUNCHDIR/lead.sh\""
} > "$LAUNCHDIR/lead.sh"
chmod +x "$LAUNCHDIR/lead.sh"

herdr server stop >/dev/null 2>&1 || true
sleep 1
[ "$MODE" = "run" ] && rm -rf "$HOME/.config/herdr/sessions/$SESSION"
sleep 0.5
( cd "$HERE" && command herdr server --session "$SESSION" >/dev/null 2>&1 & )
WORKSPACE_READY=0
for _ in $(seq 1 40); do
  herdr workspace list 2>/dev/null | grep -q '"workspaces"' && { WORKSPACE_READY=1; break; }
  sleep 0.3
done
[ "$WORKSPACE_READY" = 1 ] || echo "warning: herdr server did not report workspaces ready within 12s — continuing anyway" >&2
# Only create a workspace if this session has none. `workspace create` is unconditional
# otherwise, and on --resume Herdr has already restored the previous run's workspace — so
# every resume was adding another empty "Harness" workspace beside the real one.
if ! herdr workspace list 2>/dev/null | grep -q '"workspace_id"'; then
  herdr workspace create --label "Harness" >/dev/null 2>&1 || true
fi

# A Herdr server restart — observed for real when an unrelated `herdr plugin uninstall`
# bounced the server mid-run — destroys the workspace and every agent pane, but
# build/.launch/*.pane records survive on disk. Left alone, team.sh's duplicate-role guard
# refuses to re-hire anyone ("$ROLE is already hired") pointing at panes that no longer exist,
# and its team-cap count includes the dead records too. Prune anything stale here: after the
# server is confirmed up (so `herdr pane list` is answerable) and before this script writes
# its own lead.pane below. Runs in both run-mode and resume-mode; in run-mode build/ is
# normally fresh so this is a no-op, but a leftover build/ from a killed run is exactly when
# it matters.
# A record is stale if its pane is gone OR the pane survived with no live agent in it.
# Pane existence alone is NOT the test. A Herdr server restart RESTORES the panes — labels and
# all — while every agent process inside them is dead. Checking only pane_id therefore pruned
# nothing in exactly the case that matters, and scripts/team.sh went on refusing to re-hire
# ("already hired") for agents that no longer existed. Observed directly: after a restart the
# implementer and verifier panes came back with agent_status "unknown" and a bare shell prompt.
#
# An agent that is genuinely alive reports working/idle/blocked/done through
# atomic/extensions/herdr-state.ts, so "unknown" is the signal for an empty pane. Pruning runs
# before this script starts anything, so a live agent can never be caught by it.
live_agent_panes(){
  herdr pane list 2>/dev/null | python3 -c "
import sys,json
try: panes=json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
for p in panes:
    if (p.get('agent_status') or 'unknown') != 'unknown':
        print(p['pane_id'])
"
}
if [ -d "$LAUNCHDIR" ]; then
  # An empty result with a zero exit means the server answered and no pane holds a live agent —
  # the normal resume case, where everything should be pruned. Only a non-zero exit (the server
  # could not be reached at all) suppresses pruning.
  if LIVE_AGENT_PANES="$(live_agent_panes)"; then
    # `|| true`: a glob matching no *.pane files would otherwise abort under set -e.
    PANE_RECORDS="$(ls "$LAUNCHDIR"/*.pane 2>/dev/null)" || true
    if [ -n "$PANE_RECORDS" ]; then
      for f in $PANE_RECORDS; do
        ROLE_NAME="$(basename "$f" .pane)"
        RECORDED_PANE="$(cat "$f" 2>/dev/null || true)"
        if [ -z "$RECORDED_PANE" ] || ! printf '%s\n' "$LIVE_AGENT_PANES" | grep -qxF "$RECORDED_PANE"; then
          echo "pruned stale record: $ROLE_NAME (pane ${RECORDED_PANE:-none} has no live agent) — the role can be hired again"
          rm -f "$f"
        fi
      done
    fi
  else
    # Cannot reach the server — do NOT prune. Deleting every record because the server is
    # unreachable would be worse than the bug this is fixing: it would make a merely-offline
    # server look identical to a destroyed workspace and wipe valid records.
    echo "warning: could not reach herdr to check for stale pane records — leaving $LAUNCHDIR/*.pane untouched" >&2
  fi
fi

# The root shell pane is NOT reliably panes[0]: Herdr plugin panes carry labels ("Sidebar",
# "Explorer", …) and may register first. Select on the ABSENCE of a label.
root_pane(){
  herdr pane list 2>/dev/null | python3 -c "
import sys,json
try: panes=json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
shells=[p for p in panes if not p.get('label')]
if not shells: sys.exit(1)
print(sorted(shells,key=lambda p:p['pane_id'])[0]['pane_id'])
"
}
# On --resume the lead pane already carries the label 'lead' from a prior run (this script
# renamed it), so root_pane()'s unlabeled search would find nothing. Prefer the labelled pane;
# fall back to the unlabeled search only if no labelled pane exists yet.
lead_pane_by_label(){
  herdr pane list 2>/dev/null | python3 -c "
import sys,json
try: panes=json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
leads=[p for p in panes if p.get('label')=='lead']
if not leads: sys.exit(1)
print(sorted(leads,key=lambda p:p['pane_id'])[0]['pane_id'])
"
}
LEAD=""
if [ "$MODE" = "resume" ]; then
  for _ in $(seq 1 40); do
    LEAD="$(lead_pane_by_label || true)"
    [ -n "$LEAD" ] && break
    sleep 0.5
  done
fi
if [ -z "$LEAD" ]; then
  for _ in $(seq 1 40); do
    LEAD="$(root_pane || true)"
    [ -n "$LEAD" ] && break
    sleep 0.5
  done
fi
[ -n "$LEAD" ] || { echo "could not find a shell pane to start the lead in" >&2; exit 1; }

herdr pane rename "$LEAD" lead >/dev/null 2>&1 || true
echo "$LEAD" > "$LAUNCHDIR/lead.pane"

herdr pane send-text "$LEAD" "bash $LAUNCHDIR/lead.sh" >/dev/null
herdr pane send-keys "$LEAD" Enter >/dev/null

# DO NOT add a pane-readiness poll here. An earlier version waited for the pane's title to
# start with "atomic", and it deadlocked on the first real run: build-intake.ts opens its
# popup during session_start, and while that dialog is open the pane title stays "bash
# .../lead.sh". The title never changes, so the poll always timed out, deleted lead.pane, and
# exited — leaving a live popup with no script left to send the kickoff once it was answered.
#
# The poll existed to gate a `/name lead` send. That send is still needed (see below, where it
# now happens once IDEA.md exists) — but it does not need a poll: the wait for IDEA.md below IS
# the readiness signal, since it cannot be satisfied unless Atomic booted, rendered the popup,
# and got an answer.
#
# Nothing may be sent to this pane before IDEA.md exists: anything typed while the dialog is
# open lands IN the popup and is submitted as the human's answer.

# The popup is now up in the lead's pane. Wait for the human to answer it, then kick the lead
# into refining. (If a future Atomic lets an extension self-start a turn, this poll becomes
# unnecessary — see atomic/extensions/build-intake.ts.)
echo
echo "════════════════════════════════════════════════════════════"
if [ "$MODE" = "resume" ]; then
  # On a resume IDEA.md already exists, so build-intake.ts stays quiet and the wait below
  # returns at once. Saying "answer the question" here described a popup that never appears.
  echo " Resuming. To watch the team, open another terminal and run:"
else
  echo " To see the popup and answer the question, open another"
  echo " terminal and run:"
fi
echo
printf ' %s\n' "  herdr --session $SESSION"
echo
echo "════════════════════════════════════════════════════════════"
echo
if [ "$MODE" = "resume" ]; then
  echo "Re-attaching the lead to the existing mission…"
else
  echo "Waiting for your answer in the attached cockpit…"
fi
# Wait for the human to answer the intake popup. There is deliberately NO timeout here.
# The popup keeps the lead agent alive with the question on screen, and the two kickoff
# sends below are gated on IDEA.md existing — so giving up would strand a live agent that
# can still be answered, and --resume is unsafe then (it restarts the server and discards
# the typed answer). Wait as long as it takes; print a heartbeat so a long wait does not
# look like a hang. The human can abort with Ctrl-C, or stop the run from another terminal
# with: herdr --session $SESSION server stop
# The wait below is unbounded, so a human who gives up must get guidance instead of dying
# silently while the detached herdr server and the live lead pane keep running. On Ctrl-C or
# SIGTERM, print how to reach the still-live lead, then exit. Cleared right after the loop so
# the rest of the script keeps default signal behavior.
trap 'printf "\n[harness] Interrupted before you answered. The lead is still live in its pane.\n  Attach with:  herdr --session %s\n  Answer the question, then re-run: ./build.sh --resume\n  Or stop the run: herdr --session %s server stop\n" "$SESSION" "$SESSION" >&2; exit 130' INT TERM
WAITED=0
while [ ! -f "$BUILD/IDEA.md" ]; do
  sleep 1
  WAITED=$((WAITED + 1))
  if [ $((WAITED % 60)) -eq 0 ]; then
    printf '[harness] still waiting for your answer in the cockpit (%dm elapsed)…\n' "$((WAITED / 60))"
  fi
done
trap - INT TERM

if [ -f "$BUILD/IDEA.md" ]; then
  # Register the lead on the Intercom broker, NOW — the popup has closed (IDEA.md exists), so
  # this lands at Atomic's prompt instead of inside the dialog.
  #
  # This send is required, and an earlier version deleted it on the theory that `-n lead` at
  # launch already set the Intercom name. A real run disproved that: specialists could not
  # reach the lead at all, and the implementer sat in a `sleep` loop for 19 minutes reporting
  # "Lead still hasn't come online", with `intercom send lead` returning
  # "Message to \"lead\" was not delivered: Session not found". `-n` sets the session's display
  # name; only `/name` registers the Intercom presence name. Both are needed.
  #
  # Timing is the whole trick: sent any earlier it is typed into the intake popup and becomes
  # the human's answer. Sent here, it works. Do not move it in either direction.
  herdr pane send-text "$LEAD" "/name lead" >/dev/null
  herdr pane send-keys "$LEAD" Enter >/dev/null
  sleep 2

  if [ -f "$BUILD/MISSION.md" ]; then
    # A mission already exists — this is a resume. It may already be human-confirmed, so do
    # NOT re-refine IDEA.md or re-run the confirmation gate; that would silently rewrite a
    # mission the human already approved. Just get the lead re-oriented and moving again.
    herdr pane send-text "$LEAD" "Resume. Re-read $BUILD/MISSION.md and $BUILD/ROSTER.md (if present) to recover context, then continue the mission from where it left off. Do NOT re-refine MISSION.md and do NOT re-run the human confirmation gate — treat the mission as already confirmed. Hire more specialists with scripts/team.sh add <role> only if the mission still needs them." >/dev/null
  else
    herdr pane send-text "$LEAD" "Begin. Read $BUILD/IDEA.md, refine it into $BUILD/MISSION.md with /skill:prompt-engineer, show me the mission for confirmation, then hire your team with scripts/team.sh add <role>." >/dev/null
  fi
  herdr pane send-keys "$LEAD" Enter >/dev/null
else
  # Defensive re-check, not an interrupt guard: reachable only if IDEA.md disappears between
  # the loop's last test and this line (TOCTOU). On Ctrl-C/SIGTERM the script dies inside the
  # wait loop above and never reaches here, so the kickoff sends cannot fire without a mission.
  echo "No IDEA.md — the intake wait was interrupted before you answered. Attach a" >&2
  echo "cockpit with:  herdr --session $SESSION" >&2
  echo "answer the question, then re-run: ./build.sh --resume" >&2
fi

# Open a read-only "team chat" pane beside the lead so the human can watch the whole intercom
# conversation as one feed (intercom-bridge.ts writes it — see
# specs/2026-08-14-intercom-team-chat-pane.md). Idempotent: skip if a team-chat pane already
# exists (e.g. on --resume). Best-effort: a failure here must never fail the run, so every
# herdr call swallows its error.
if ! herdr pane list 2>/dev/null | python3 -c "
import sys, json
try: panes = json.load(sys.stdin)['result']['panes']
except Exception: sys.exit(1)
sys.exit(0 if any(p.get('label') == 'team-chat' for p in panes) else 1)
"; then
  CHATPANE="$(herdr pane split "$LEAD" --direction right --ratio 0.35 --no-focus --cwd "$HERE" 2>/dev/null \
    | python3 -c "import sys,json;print(json.load(sys.stdin)['result']['pane']['pane_id'])" 2>/dev/null || true)"
  if [ -n "$CHATPANE" ]; then
    herdr pane rename "$CHATPANE" team-chat >/dev/null 2>&1 || true
    echo "$CHATPANE" > "$LAUNCHDIR/team-chat.pane"
    # Pass the feed and the team's intercom group so the viewer's "chat" peer joins the same group
    # as the agents (otherwise the human could not message them).
    herdr pane send-text "$CHATPANE" "TEAMCHAT_FEED=$BUILD/team-chat.log ATOMIC_INTERCOM_GROUP=$GROUP ./scripts/team-chat.sh" >/dev/null 2>&1 || true
    herdr pane send-keys "$CHATPANE" Enter >/dev/null 2>&1 || true
  fi
fi

if [ "$MODE" = "resume" ]; then
  HEADLINE=" The lead is back. It is re-reading the mission and continuing."
else
  HEADLINE=" The lead is live. It will ask what to build, then hire."
fi

cat <<EOF

════════════════════════════════════════════════════════════
$HEADLINE
════════════════════════════════════════════════════════════
 WATCH:    herdr --session $SESSION
 ROSTER:   cat $BUILD/ROSTER.md
 MISSION:  cat $BUILD/MISSION.md
 STOP:     herdr --session $SESSION server stop
 CHAT:     opens automatically in the 'team-chat' pane · reopen: ./scripts/team-chat.sh

 Output lands in: $BUILD
EOF
