#!/usr/bin/env bash
# generated by team.sh — starts the 'implementer' agent
export ATOMIC_ROLE=implementer
export ATOMIC_INTERCOM_GROUP=cockpit
export BUILD_DIR=/Users/mp/git-repos/atomic-cockpit/build
export TEAMCHAT_FEED=/Users/mp/git-repos/atomic-cockpit/build/team-chat.log
cd "/Users/mp/git-repos/atomic-cockpit"
atomic -e /Users/mp/git-repos/atomic-cockpit/atomic/extensions/herdr-state.ts -e /Users/mp/git-repos/atomic-cockpit/atomic/extensions/intercom-bridge.ts --provider anthropic --model claude-sonnet-5 -n implementer \
  --append-system-prompt "$(cat /Users/mp/git-repos/atomic-cockpit/team/implementer.md)" \
  --append-system-prompt "$(cat /Users/mp/git-repos/atomic-cockpit/team/TRANSPORT.md)" \
  2> >(tee -a /Users/mp/git-repos/atomic-cockpit/build/.launch/implementer.stderr.log >&2)
status=$?
echo; echo "[cockpit] the 'implementer' session exited (status $status). Pane kept open."
echo "[cockpit] stderr: /Users/mp/git-repos/atomic-cockpit/build/.launch/implementer.stderr.log"
echo "[cockpit] restart with: bash /Users/mp/git-repos/atomic-cockpit/build/.launch/implementer.sh"
