#!/usr/bin/env bash
# generated by build.sh — starts the 'lead' agent
export ATOMIC_ROLE=lead
export ATOMIC_INTERCOM_GROUP=cockpit
export BUILD_DIR=/Users/mp/git-repos/atomic-cockpit/build
export TEAMCHAT_FEED=/Users/mp/git-repos/atomic-cockpit/build/team-chat.log
export ATOMIC_PROVIDER=anthropic
export ATOMIC_MODEL=claude-sonnet-5
export HERDR_SESSION=cockpit
cd "/Users/mp/git-repos/atomic-cockpit"
atomic -e /Users/mp/git-repos/atomic-cockpit/atomic/extensions/herdr-state.ts -e /Users/mp/git-repos/atomic-cockpit/atomic/extensions/build-intake.ts -e /Users/mp/git-repos/atomic-cockpit/atomic/extensions/intercom-bridge.ts --provider anthropic --model claude-sonnet-5 -n lead \
  --append-system-prompt "$(cat /Users/mp/git-repos/atomic-cockpit/team/lead.md)" \
  --append-system-prompt "$(cat /Users/mp/git-repos/atomic-cockpit/team/TRANSPORT.md)" \
  2> >(tee -a /Users/mp/git-repos/atomic-cockpit/build/.launch/lead.stderr.log >&2)
status=$?
echo; echo "[cockpit] the lead session exited (status $status). Pane kept open."
echo "[cockpit] stderr: /Users/mp/git-repos/atomic-cockpit/build/.launch/lead.stderr.log"
echo "[cockpit] restart with: bash /Users/mp/git-repos/atomic-cockpit/build/.launch/lead.sh"
