#!/usr/bin/env bash
# generated by build.sh — starts the 'lead' agent
export ATOMIC_ROLE=lead
export ATOMIC_INTERCOM_GROUP=harness
export BUILD_DIR=/Users/mp/git-repos/agentic-engineering-harness/build
export TEAMCHAT_FEED=/Users/mp/git-repos/agentic-engineering-harness/build/team-chat.log
export ATOMIC_PROVIDER=anthropic
export ATOMIC_MODEL=claude-sonnet-5
export HERDR_SESSION=harness
cd "/Users/mp/git-repos/agentic-engineering-harness"
atomic -e /Users/mp/git-repos/agentic-engineering-harness/atomic/extensions/herdr-state.ts -e /Users/mp/git-repos/agentic-engineering-harness/atomic/extensions/build-intake.ts -e /Users/mp/git-repos/agentic-engineering-harness/atomic/extensions/intercom-bridge.ts --provider anthropic --model claude-sonnet-5 -n lead \
  --append-system-prompt "$(cat /Users/mp/git-repos/agentic-engineering-harness/team/lead.md)" \
  --append-system-prompt "$(cat /Users/mp/git-repos/agentic-engineering-harness/team/TRANSPORT.md)" \
  2> >(tee -a /Users/mp/git-repos/agentic-engineering-harness/build/.launch/lead.stderr.log >&2)
status=$?
echo; echo "[harness] the lead session exited (status $status). Pane kept open."
echo "[harness] stderr: /Users/mp/git-repos/agentic-engineering-harness/build/.launch/lead.stderr.log"
echo "[harness] restart with: bash /Users/mp/git-repos/agentic-engineering-harness/build/.launch/lead.sh"
