#!/usr/bin/env bash
# generated by team.sh — starts the 'researcher' agent
export ATOMIC_ROLE=researcher
export ATOMIC_INTERCOM_GROUP=harness
export BUILD_DIR=/Users/mp/git-repos/agentic-engineering-harness/build
export TEAMCHAT_FEED=/Users/mp/git-repos/agentic-engineering-harness/build/team-chat.log
cd "/Users/mp/git-repos/agentic-engineering-harness"
atomic -e /Users/mp/git-repos/agentic-engineering-harness/atomic/extensions/herdr-state.ts -e /Users/mp/git-repos/agentic-engineering-harness/atomic/extensions/intercom-bridge.ts --provider anthropic --model claude-sonnet-5 -n researcher \
  --append-system-prompt "$(cat /Users/mp/git-repos/agentic-engineering-harness/team/researcher.md)" \
  --append-system-prompt "$(cat /Users/mp/git-repos/agentic-engineering-harness/team/TRANSPORT.md)" \
  2> >(tee -a /Users/mp/git-repos/agentic-engineering-harness/build/.launch/researcher.stderr.log >&2)
status=$?
echo; echo "[harness] the 'researcher' session exited (status $status). Pane kept open."
echo "[harness] stderr: /Users/mp/git-repos/agentic-engineering-harness/build/.launch/researcher.stderr.log"
echo "[harness] restart with: bash /Users/mp/git-repos/agentic-engineering-harness/build/.launch/researcher.sh"
