#!/usr/bin/env bash
# team.sh — the lead hires its team with this.
#
#   scripts/team.sh roles                                  # what roles exist, and when to hire them
#   scripts/team.sh add verifier --reason "prove the CLI"  # hire one
#   scripts/team.sh list                                   # who is hired so far
#
# `add` splits a pane, boots that role's Atomic session with its brief, names it for
# intercom, and appends the hire (with the lead's reason) to build/ROSTER.md.
#
# Verified against Atomic 0.9.12 and Herdr 0.8.0. Bash 3.2 safe.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
BUILD="${BUILD_DIR:-$HERE/build}"
LAUNCHDIR="$BUILD/.launch"
SESSION="${HERDR_SESSION:-harness}"
GROUP="${ATOMIC_INTERCOM_GROUP:-harness}"
PROVIDER="${ATOMIC_PROVIDER:-anthropic}"
MODEL="${ATOMIC_MODEL:-claude-sonnet-5}"
MAX_AGENTS=8
export PATH="$HOME/.local/bin:$PATH"
herdr(){ command herdr --session "$SESSION" "$@"; }

usage(){ sed -n '2,11p' "$0"; exit "${1:-0}"; }
[ $# -gt 0 ] || usage 2

CMD="$1"; shift

case "$CMD" in
  roles)
    cat "$HERE/team/ROLES.md"
    exit 0
    ;;
  list)
    if [ -f "$BUILD/ROSTER.md" ]; then cat "$BUILD/ROSTER.md"; else echo "No one hired yet."; fi
    exit 0
    ;;
  add) : ;;
  *) echo "unknown command: $CMD" >&2; usage 2 ;;
esac

ROLE="${1:-}"; shift || true
REASON=""
while [ $# -gt 0 ]; do
  case "$1" in
    --reason) REASON="$2"; shift ;;
    --force)  MAX_AGENTS=99 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac; shift
done

[ -n "$ROLE" ] || { echo "usage: team.sh add <role> --reason \"...\"" >&2; exit 2; }

# Compute the valid-role list once and check membership against it, so the gate and the
# error message's "available" list can never drift apart. team/ROLES.md, team/TRANSPORT.md,
# and team/lead.md are real files under team/ but are not hireable roles — excluded here.
VALID_ROLES="$(ls "$HERE/team" | sed 's/\.md$//' | grep -v -E '^(ROLES|TRANSPORT|lead)$')"
if ! printf '%s\n' "$VALID_ROLES" | grep -qx "$ROLE"; then
  echo "no such role: $ROLE" >&2
  echo "available: $(printf '%s\n' "$VALID_ROLES" | tr '\n' ' ')" >&2
  exit 2
fi
[ -n "$REASON" ] || { echo "--reason is required: say why this mission needs a $ROLE" >&2; exit 2; }
[ -f "$BUILD/MISSION.md" ] || { echo "no $BUILD/MISSION.md yet — refine the idea before hiring" >&2; exit 2; }

# Refuse duplicates: two sessions with the same name are unaddressable over intercom.
if [ -f "$LAUNCHDIR/$ROLE.pane" ]; then
  echo "$ROLE is already hired (pane $(cat "$LAUNCHDIR/$ROLE.pane"))." >&2
  exit 2
fi

HIRED=$(ls "$LAUNCHDIR"/*.pane 2>/dev/null | wc -l | tr -d ' ') || true
if [ "$HIRED" -ge "$MAX_AGENTS" ]; then
  echo "team is at its cap of $MAX_AGENTS agents. Decompose, or re-run with --force." >&2
  exit 2
fi

# Split the most recently created pane, alternating right/down, so the grid stays roughly
# square as the team grows.
LAST_PANE="$(ls -t "$LAUNCHDIR"/*.pane 2>/dev/null | head -1)" || true
TARGET="$(cat "${LAST_PANE:-$LAUNCHDIR/lead.pane}")"
if [ $((HIRED % 2)) -eq 1 ]; then DIRECTION=down; else DIRECTION=right; fi

PANE=$(herdr pane split "$TARGET" --direction "$DIRECTION" --no-focus --cwd "$HERE" \
  | python3 -c "import sys,json;print(json.load(sys.stdin)['result']['pane']['pane_id'])")
herdr pane rename "$PANE" "$ROLE" >/dev/null 2>&1 || true
echo "$PANE" > "$LAUNCHDIR/$ROLE.pane"

{
  echo '#!/usr/bin/env bash'
  echo "# generated by team.sh — starts the '$ROLE' agent"
  printf 'export ATOMIC_ROLE=%q\n' "$ROLE"
  printf 'export ATOMIC_INTERCOM_GROUP=%q\n' "$GROUP"
  printf 'export BUILD_DIR=%q\n' "$BUILD"
  echo "cd \"$HERE\""
  printf 'atomic -e %q --provider %q --model %q -n %q \\\n' \
    "$HERE/atomic/extensions/herdr-state.ts" "$PROVIDER" "$MODEL" "$ROLE"
  printf '  --append-system-prompt "$(cat %q)" \\\n' "$HERE/team/$ROLE.md"
  printf '  --append-system-prompt "$(cat %q)" \\\n' "$HERE/team/TRANSPORT.md"
  printf '  2> >(tee -a %q >&2)\n' "$LAUNCHDIR/$ROLE.stderr.log"
  echo 'status=$?'
  echo "echo; echo \"[harness] the '$ROLE' session exited (status \$status). Pane kept open.\""
  echo "echo \"[harness] stderr: $LAUNCHDIR/$ROLE.stderr.log\""
  echo "echo \"[harness] restart with: bash $LAUNCHDIR/$ROLE.sh\""
} > "$LAUNCHDIR/$ROLE.sh"
chmod +x "$LAUNCHDIR/$ROLE.sh"

herdr pane send-text "$PANE" "bash $LAUNCHDIR/$ROLE.sh" >/dev/null
herdr pane send-keys "$PANE" Enter >/dev/null

ATOMIC_UP=0
for _ in $(seq 1 60); do
  if herdr pane list 2>/dev/null | python3 -c "
import sys,json
p=[x for x in json.load(sys.stdin)['result']['panes'] if x['pane_id']=='$PANE']
sys.exit(0 if p and (p[0].get('terminal_title_stripped') or '').startswith('atomic') else 1)
" 2>/dev/null; then ATOMIC_UP=1; break; fi
  sleep 1
done
[ "$ATOMIC_UP" = 1 ] || {
  rm -f "$LAUNCHDIR/$ROLE.pane"
  echo "Atomic did not reach its prompt in the '$ROLE' pane (pane $PANE) within 60s." >&2
  echo "Removed $LAUNCHDIR/$ROLE.pane so the role can be retried. Inspect the pane, then" >&2
  echo "re-run: scripts/team.sh add $ROLE --reason \"...\"" >&2
  exit 1
}

# ORDER MATTERS: /name before the session's first intercom call, or it registers as
# subagent-chat-<id> and is unaddressable by role forever.
herdr pane send-text "$PANE" "/name $ROLE" >/dev/null
herdr pane send-keys "$PANE" Enter >/dev/null
sleep 2

herdr pane send-text "$PANE" "You are the \"$ROLE\" agent. Read $BUILD/MISSION.md and your role brief. Then your FIRST action must be: intercom send to \"lead\" with the message \"$ROLE ready\" — this registers you with the broker so the lead can reach you. Then wait; the lead will assign your work." >/dev/null
herdr pane send-keys "$PANE" Enter >/dev/null

if [ ! -f "$BUILD/ROSTER.md" ]; then
  printf '# Roster\n\nWho was hired for this mission, and why.\n\n| Role | Pane | Reason |\n|---|---|---|\n' > "$BUILD/ROSTER.md"
fi
printf '| `%s` | %s | %s |\n' "$ROLE" "$PANE" "$REASON" >> "$BUILD/ROSTER.md"

echo "✓ hired $ROLE in pane $PANE"
